export const FOOD_LIST = [
    {
      id: 1,
      name: "Salmorejo cordobés",
      description: "Crema fría de tomate con pan, ajo y aceite de oliva.",
      price: 5.5,
      cal: 220,
      picture: "",
      ingredientes: ["tomate", "pan", "ajo", "aceite de oliva", "sal", "huevo cocido", "jamón serrano"],
      allergens: ["gluten", "egg"],
      category: [1],
    },
    {
      id: 2,
      name: "Gazpacho andaluz",
      description: "Sopa fría de verduras frescas ideal para el verano.",
      price: 4.5,
      cal: 180,
      picture: "",
      ingredientes: ["tomate", "pepino", "pimiento", "cebolla", "ajo", "aceite de oliva", "vinagre", "sal"],
      allergens: ["sulphur"],
      category: [1],
    },
    {
      id: 3,
      name: "Flamenquín cordobés",
      description: "Rollito empanado de lomo relleno de jamón serrano.",
      price: 7,
      cal: 450,
      picture: "",
      ingredientes: ["lomo", "jamón serrano", "huevo", "pan rallado", "aceite"],
      allergens: ["egg", "gluten"],
      category: [2],
    },
    {
      id: 4,
      name: "Papas aliñás",
      description: "Ensalada de patata con cebolla, perejil y aceite.",
      price: 3.5,
      cal: 200,
      picture: "",
      ingredientes: ["patata", "cebolla", "perejil", "vinagre", "aceite de oliva"],
      allergens: [
        "soy",
        "crustacean",
        "celery",
        "mustard",
        "sesame",
        "mollusk",
        "lupine",
      ],
      category: [1],
    },
    {
      id: 5,
      name: "Pescaito frito",
      description: "Fritura de pescados pequeños típica de la costa andaluza.",
      price: 8,
      cal: 400,
      picture: "",
      ingredientes: ["boquerones", "calamares", "harina", "aceite"],
      allergens: ["fish", "gluten"],
      category: [2],
    },
    {
      id: 6,
      name: "Tortilla de camarones",
      description: "Fritura crujiente de camarones y harina.",
      price: 4,
      cal: 250,
      picture: "",
      ingredientes: ["camarones", "harina", "cebolla", "perejil", "agua", "aceite"],
      allergens: ["crustaceans", "gluten"],
      category: [2],
    },
    {
      id: 7,
      name: "Huevos a la flamenca",
      description: "Huevo al horno con tomate, guisantes, chorizo y jamón.",
      price: 6.5,
      cal: 370,
      picture: "",
      ingredientes: ["huevo", "chorizo", "guisantes", "tomate", "jamón"],
      allergens: ["egg"],
      category: [2],
    },
    {
      id: 8,
      name: "Choco frito",
      description: "Sepia frita al estilo gaditano.",
      price: 7,
      cal: 350,
      picture: "",
      ingredientes: ["sepia", "harina", "sal", "aceite"],
      allergens: ["molluscs", "gluten"],
      category: [2],
    },
    {
      id: 9,
      name: "Cazón en adobo",
      description: "Trozos de pescado marinados y fritos.",
      price: 6,
      cal: 330,
      picture: "",
      ingredientes: ["cazón", "vinagre", "orégano", "pimentón", "harina"],
      allergens: ["fish", "gluten"],
      category: [2],
    },
    {
      id: 10,
      name: "Berza jerezana",
      description: "Guiso con col, garbanzos y carne.",
      price: 7.5,
      cal: 480,
      picture: "",
      ingredientes: ["col", "garbanzos", "morcilla", "chorizo", "patata"],
      allergens: [],
      category: [3],
    },
    {
      id: 11,
      name: "Migas andaluzas",
      description: "Pan frito con ajo, chorizo y pimientos.",
      price: 5,
      cal: 500,
      picture: "",
      ingredientes: ["pan", "ajo", "chorizo", "pimiento", "aceite"],
      allergens: ["gluten"],
      category: [3],
    },
    {
      id: 12,
      name: "Espinacas con garbanzos",
      description: "Plato típico sevillano muy especiado.",
      price: 4.5,
      cal: 300,
      picture: "",
      ingredientes: ["espinacas", "garbanzos", "ajo", "comino", "pimentón"],
      allergens: [],
      category: [2],
    },
    {
      id: 13,
      name: "Ajo blanco malagueño",
      description: "Sopa fría de almendras, pan y ajo.",
      price: 4.5,
      cal: 230,
      picture: "",
      ingredientes: ["almendras", "ajo", "pan", "aceite", "vinagre"],
      allergens: ["gluten", "nuts"],
      category: [1],
    },
    {
      id: 14,
      name: "Rabo de toro",
      description: "Estofado de rabo de vaca típico de Córdoba.",
      price: 10,
      cal: 600,
      picture: "",
      ingredientes: ["rabo de toro", "vino tinto", "zanahoria", "cebolla"],
      allergens: [],
      category: [3],
    },
    {
      id: 15,
      name: "Albondiguillas en salsa",
      description: "Albóndigas con salsa de almendras o tomate.",
      price: 6,
      cal: 420,
      picture: "",
      ingredientes: ["carne picada", "pan rallado", "huevo", "almendras"],
      allergens: ["egg", "gluten", "nuts"],
      category: [2],
    },
    {
      id: 16,
      name: "Serranito",
      description: "Bocadillo de lomo, jamón serrano y pimiento verde.",
      price: 5.5,
      cal: 550,
      picture: "",
      ingredientes: ["pan", "lomo", "jamón serrano", "pimiento", "tomate", "mayonesa"],
      allergens: ["gluten", "egg"],
      category: [2],
    },
    {
      id: 17,
      name: "Poleá",
      description: "Postre de harina, leche, azúcar y anís.",
      price: 3,
      cal: 320,
      picture: "",
      ingredientes: ["harina", "leche", "azúcar", "anís", "aceite"],
      allergens: ["gluten", "milk"],
      category: [4],
    },
    {
      id: 18,
      name: "Piononos de Santa Fe",
      description: "Dulce típico de Granada, pequeño y empapado en licor.",
      price: 2,
      cal: 150,
      picture: "",
      ingredientes: ["harina", "huevo", "azúcar", "licor", "canela"],
      allergens: ["gluten", "egg"],
      category: [4],
    },
    {
      id: 19,
      name: "Tarta de Santiago",
      description: "Tarta de almendra con azúcar glas.",
      price: 3,
      cal: 350,
      picture: "",
      ingredientes: ["almendras", "huevo", "azúcar", "canela", "limón"],
      allergens: ["egg", "nuts"],
      category: [4],
    },
    {
      id: 20,
      name: "Callos a la andaluza",
      description: "Guiso de tripas de ternera con chorizo y morcilla.",
      price: 6.5,
      cal: 550,
      picture: "",
      ingredientes: ["callos", "chorizo", "morcilla", "garbanzos", "pimentón"],
      allergens: [],
      category: [3],
    },
    {
      id: 21,
      name: "Cocido andaluz",
      description: "Versión sureña del cocido con más verduras.",
      price: 7.5,
      cal: 600,
      picture: "",
      ingredientes: ["garbanzos", "carne", "verdura", "patata", "chorizo"],
      allergens: [],
      category: [3],
    },
    {
      id: 22,
      name: "Zarangollo",
      description: "Revuelto murciano con huevo, cebolla y calabacín.",
      price: 4,
      cal: 280,
      picture: "",
      ingredientes: ["huevo", "cebolla", "calabacín", "aceite"],
      allergens: ["egg"],
      category: [2],
    },
    {
      id: 23,
      name: "Pisto andaluz",
      description: "Verduras guisadas con tomate y huevo frito.",
      price: 5,
      cal: 300,
      picture: "",
      ingredientes: ["calabacín", "pimiento", "tomate", "cebolla", "huevo"],
      allergens: ["egg"],
      category: [2],
    },
    {
      id: 24,
      name: "Papas con choco",
      description: "Guiso de patatas con sepia típico de Huelva.",
      price: 6,
      cal: 400,
      picture: "",
      ingredientes: ["patatas", "sepia", "cebolla", "ajo", "laurel"],
      allergens: ["molluscs"],
      category: [3],
    },
    {
      id: 25,
      name: "Berenjenas con miel",
      description: "Rodajas de berenjena frita con miel de caña.",
      price: 4,
      cal: 270,
      picture: "",
      ingredientes: ["berenjena", "harina", "miel de caña"],
      allergens: ["gluten"],
      category: [2],
    },

    {
        id: 26,
        name: "Gazpachuelo malagueño",
        description: "Sopa caliente con mayonesa, patatas y pescado.",
        price: 5.5,
        cal: 320,
        picture: "",
        ingredientes: ["patatas", "pescado blanco", "mayonesa", "agua", "limón"],
        allergens: ["fish", "egg"],
        category: [3],
    },
    {
        id: 27,
        name: "Olla de San Antón",
        description: "Guiso granadino con habas, arroz, morcilla y hueso de jamón.",
        price: 7,
        cal: 600,
        picture: "",
        ingredientes: ["habas", "arroz", "morcilla", "jamón", "patatas"],
        allergens: [],
        category: [3],
    },
    {
        id: 28,
        name: "Pipirrana",
        description: "Ensalada fresca de Jaén con tomate, pimiento, atún y huevo.",
        price: 4,
        cal: 220,
        picture: "",
        ingredientes: ["tomate", "pimiento", "atún", "cebolla", "huevo duro"],
        allergens: ["fish", "egg"],
        category: [1],
    },
    {
        id: 29,
        name: "Tortas de aceite",
        description: "Dulces crujientes con sabor a anís y ajonjolí.",
        price: 1.5,
        cal: 180,
        picture: "",
        ingredientes: ["harina", "aceite de oliva", "azúcar", "anís", "sésamo"],
        allergens: ["gluten", "sesame"],
        category: [4],
    },
    {
        id: 30,
        name: "Ensaladilla rusa",
        description: "Patata, mayonesa, atún y verduras.",
        price: 4,
        cal: 350,
        picture: "",
        ingredientes: ["patata", "zanahoria", "guisantes", "atún", "mayonesa", "huevo"],
        allergens: ["egg", "fish"],
        category: [1],
    },
    {
        id: 31,
        name: "Alfajores de Medina",
        description: "Dulce navideño gaditano con miel, almendras y especias.",
        price: 2,
        cal: 200,
        picture: "",
        ingredientes: ["almendras", "miel", "canela", "harina"],
        allergens: ["nuts", "gluten"],
        category: [4],
    },
    {
        id: 32,
        name: "Fritá de pulpo",
        description: "Salteado de pulpo con pimientos y tomate.",
        price: 7,
        cal: 300,
        picture: "",
        ingredientes: ["pulpo", "pimiento", "tomate", "aceite"],
        allergens: ["molluscs"],
        category: [2],
    },
    {
        id: 33,
        name: "Caballa con piriñaca",
        description: "Caballa a la plancha con ensalada típica gaditana.",
        price: 6,
        cal: 280,
        picture: "",
        ingredientes: ["caballa", "pimiento", "cebolla", "tomate", "vinagre", "aceite"],
        allergens: ["fish"],
        category: [2],
    },
    {
        id: 34,
        name: "Churros con chocolate",
        description: "Masa frita acompañada con chocolate caliente.",
        price: 3.5,
        cal: 500,
        picture: "",
        ingredientes: ["harina", "agua", "aceite", "chocolate", "azúcar"],
        allergens: ["gluten", "milk"],
        category: [4],
    },
    {
        id: 35,
        name: "Roscos de vino",
        description: "Dulces de vino dulce y especias típicos de Navidad.",
        price: 2,
        cal: 160,
        picture: "",
        ingredientes: ["harina", "vino dulce", "anís", "azúcar"],
        allergens: ["gluten"],
        category: [4],
    },
    {
        id: 36,
        name: "Tarta de queso andaluza",
        description: "Tarta de queso suave con miel de caña.",
        price: 4,
        cal: 420,
        picture: "",
        ingredientes: ["queso crema", "huevo", "azúcar", "harina", "miel de caña"],
        allergens: ["milk", "egg", "gluten"],
        category: [4],
    },
    {
        id: 37,
        name: "Mojama de atún",
        description: "Atún curado y cortado en lonchas finas.",
        price: 8,
        cal: 250,
        picture: "",
        ingredientes: ["atún", "sal"],
        allergens: ["fish"],
        category: [1],
    },
    {
        id: 38,
        name: "Pan cateto",
        description: "Pan típico andaluz, denso y rústico.",
        price: 1,
        cal: 150,
        picture: "",
        ingredientes: ["harina", "agua", "levadura", "sal"],
        allergens: ["gluten"],
        category: [5],
    },
    {
        id: 39,
        name: "Remojón granadino",
        description: "Ensalada de naranja con bacalao y aceitunas.",
        price: 5,
        cal: 230,
        picture: "",
        ingredientes: ["naranja", "bacalao", "aceitunas", "aceite de oliva", "cebolla"],
        allergens: ["fish"],
        category: [1],
    },
    {
        id: 40,
        name: "Almejas a la marinera",
        description: "Almejas en salsa de vino blanco, ajo y perejil.",
        price: 9,
        cal: 270,
        picture: "",
        ingredientes: ["almejas", "vino blanco", "ajo", "perejil", "harina"],
        allergens: ["molluscs", "gluten"],
        category: [2],
    },
    {
        id: 41,
        name: "Empanada gallega",
        description: "Empanada rellena de atún o carne, típica del norte.",
        price: 4,
        cal: 380,
        picture: "",
        ingredientes: ["harina", "atún", "cebolla", "pimiento", "tomate"],
        allergens: ["gluten", "fish"],
        category: [2],
    },
    {
        id: 42,
        name: "Paella",
        description: "Arroz cocinado con mariscos, verduras o carne.",
        price: 8,
        cal: 500,
        picture: "",
        ingredientes: ["arroz", "marisco", "pollo", "judía verde", "azafrán"],
        allergens: ["crustaceans", "molluscs"],
        category: [2],
    },
    {
        id: 43,
        name: "Tortilla española",
        description: "Tortilla de patata con o sin cebolla.",
        price: 3.5,
        cal: 350,
        picture: "",
        ingredientes: ["huevo", "patata", "aceite", "cebolla"],
        allergens: ["egg"],
        category: [2],
    },
    {
        id: 44,
        name: "Fabada asturiana",
        description: "Guiso contundente de fabes, chorizo y morcilla.",
        price: 8,
        cal: 650,
        picture: "",
        ingredientes: ["fabes", "chorizo", "morcilla", "panceta"],
        allergens: [],
        category: [3],
    },
    {
        id: 45,
        name: "Caldereta de cordero",
        description: "Estofado de cordero con vino y verduras.",
        price: 9,
        cal: 500,
        picture: "",
        ingredientes: ["cordero", "vino tinto", "ajo", "pimiento", "laurel"],
        allergens: [],
        category: [3],
    },
    {
        id: 46,
        name: "Pulpo a la gallega",
        description: "Pulpo cocido con pimentón, sal y aceite.",
        price: 10,
        cal: 280,
        picture: "",
        ingredientes: ["pulpo", "pimentón", "sal", "aceite de oliva"],
        allergens: ["molluscs"],
        category: [2],
    },
    {
        id: 47,
        name: "Cordero al horno",
        description: "Pierna de cordero asada con patatas y especias.",
        price: 12,
        cal: 700,
        picture: "",
        ingredientes: ["cordero", "patatas", "ajo", "romero", "vino blanco"],
        allergens: [],
        category: [3],
    },
    {
        id: 48,
        name: "Jamón ibérico",
        description: "Jamón curado de cerdo ibérico, cortado fino.",
        price: 10,
        cal: 250,
        picture: "",
        ingredientes: ["jamón ibérico"],
        allergens: [],
        category: [1],
    },
    {
        id: 49,
        name: "Croquetas caseras",
        description: "Croquetas de jamón, pollo u otro relleno.",
        price: 4,
        cal: 400,
        picture: "",
        ingredientes: ["harina", "leche", "jamón", "huevo", "pan rallado"],
        allergens: ["gluten", "milk", "egg"],
        category: [2],
    },
    {
        id: 50,
        name: "Arroz caldoso",
        description: "Arroz meloso con marisco o carne.",
        price: 8,
        cal: 450,
        picture: "",
        ingredientes: ["arroz", "marisco", "caldo", "ajo", "pimiento"],
        allergens: ["crustaceans", "molluscs"],
        category: [3],
    }      
] as const;
  